### ISSUE TITLE
Not working, as only always check dependences 

### ISSUE THREAD

**Issue by JonhSilver** [cracker0dks/CaptchaSolver#1]
Not working, as only always check dependences 
![Screenshot_2](https://user-images.githubusercontent.com/24619483/61200586-99899700-a6ea-11e9-9b89-2b621ada7ea1.png)

**Comment by cracker0dks** [comment]
do you get a "node_modules" folder in the directory after the first run?

**Comment by JonhSilver** [comment]
no I don't have a "node_modules" in JDownloader 2.0 folder

**Comment by cracker0dks** [comment]
this should be a rights problem or something. I released a standalone version working without npm installed and all deps inside: Just download the zip from: https://github.com/cracker0dks/CaptchaSolver/releases/download/1.4.1_standalone/CaptchaSolver_1.4.1_standalone.zip
and try again.
