### ISSUE TITLE
Complete the startup instructions

### ISSUE THREAD

**Issue by AntonGsv** [cracker0dks/CaptchaSolver#12]
It is not clear from the current instructions what steps to take to get a minimally working example. I tried to install it on Windows, but at the step `restart JD2 and start downloading` I don't understand what to do. 
* What is JD2?
* How can I restart it if I didn't start it?
* What do I need to download additionally?

**Comment by cracker0dks** [comment]
Hey, 
JD2 is short for JDownloader 2. 
That is a download manager. Please take a look what it does first, this CaptchaSolver is just a "plugin" so JD2 don't ask for a captcha if you download files from a [supported hosters](https://github.com/cracker0dks/CaptchaSolver#6-digits-captcha-new)
You need to install JD2 first of course :)

**Comment by AntonGsv** [comment]
@cracker0dks Thank you for your reply. Can you tell me what steps to take to locally detect text on the captcha? I think this is a duplicate question [https://github.com/cracker0dks/CaptchaSolver/issues/9](https://github.com/cracker0dks/CaptchaSolver/issues/9), but the answers from this thread did not help me.
* clone the repository
* go to the directory with the project
* run `cd "JDownloader 2.0/tools/offlineCaptchaSolver/darknet64"`
* run `test.bat` to make sure everything works

But when I run `test.bat` (or the command `darknet_no_gpu.exe detector test data/obj.data yolov3tinyobj.cfg yolov3tinyobjLast.weights -dont_show temp.jpg` directly I get no result or error message).
* Is there anything else I need to do besides the steps above? 
* Why do I need JDownloader 2?

**Comment by cracker0dks** [comment]
You don't need JDownloader 2 but this plugin is written for it. If you run test.bat (or the command) without an error, the tool already solved the captcha stored in the "temp.jpg" and wrote the result to the console: 
```
temp.jpg: Predicted in 68.543000 milli-seconds.
 e: 99%                                                                                                                  
h: 74%                                                                                                                  
C: 100%                                                                                                                 
Y: 99%                                                                                                                  
C: 100%                                                                                                                 
1: 99%
```
The letter in front of the : is what the algorithm "thinks" the solution is, and after the : is the percent of how certain it is. 

You can change the temp.jpg to your own captcha and run again to slove your own captcha.

**Comment by AntonGsv** [comment]
I was getting an error `msvcr100.dll is missing`, but when running it from the console, the error was not displayed. Fixed it as described in [readme.md](https://github.com/cracker0dks/CaptchaSolver/blob/master/README.md).
