### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by MSHClivingston** [cracker0dks/CaptchaSolver#17]
I'm aware that this site section of the site is probably considered "serious", but I have no other means of  contacting you. Sorry if that's a problem.

The solver doesn't work. JD2 gets stuck in an infinite loop of "starting..." -> "captcha recognition" and that's it. Tested with Fileboom, Tezfiles and Filejoker. Tried test.bat and it didn't show any errors.

I'm using the latest versions of both your solver and JD2 on Win10. I updated to 2.0.5 a few days ago because the old version (don't know which one that was, unfortunately) stopped working a few weeks ago. Even then it only worked with Fileboom and Tezfiles, but not Filejoker.

I'd be grateful if you could help me out. Your work is very much appreciated!

**Comment by cracker0dks** [comment]
Hey, yeah Im aware of that issue. They changed the captcha a bit some days ago and I also added a quick dirty fix be able to at least solve them: https://github.com/cracker0dks/CaptchaSolver/commit/531443c1735de3dc908ab7e376faf9b6e293d9e8
So it seams to be stuck in an infinite loop, but will solve it eventually (About 100 tries i guess). I didnt had the time for a propper fix yet... but I want to add one in the future.

**Comment by MSHClivingston** [comment]
Thanks for the reply.

Do you know any solvers (like yours) that work with Rapidgator captchas? They haven't changed in years and they look... trivial. Real words, very legible font.

**Comment by cracker0dks** [comment]
No, dont know any, can you post a few example captchas from Rapidgator so I can have a look?

Btw: check out the latest release, should work better than the version we had before: https://github.com/cracker0dks/CaptchaSolver/releases/tag/v2.1.0

**Comment by MSHClivingston** [comment]
I  only have one (the first one) and I added one I found with Google:

https://oshi.at/dxxA
https://oshi.at/vova

By the way, their database can't be all that big because I enter them pretty often and I've definitely seen some of them 2-3 times already. They've looked the same (colors, font) for at least 3 years, I think.

**Comment by cracker0dks** [comment]
mmm then maybe it is better not to "learn" this  captcha type but to create some sort of a database... I will look into it, but cant promise anything

**Comment by MSHClivingston** [comment]
Hey, all three hosts work now! Good job! Keeping my fingers crossed that it'll stay that way for a while.

If you can make those work, you can make Rapidgator work as well, no? I'm no coder, but it definitely looks easier.

**Comment by cracker0dks** [comment]
Yeah as human it seems to be easier... but we have different things that makes it complicated
1. Different fonts (we cant just train it to one font like the k2s captcha. The generator for my training data also needs to support different fonts
2. we have words, so we need to detect spaces in between them 
3. Placement and angle is random (The generator needs to support this)
4.  We also have distortion sometimes (The generator needs to support this)
5. We dont have a fixed length of captchas chars (We cant proof and remove weak detected chars)

So I think I try to build a  captcha database for rapidgator and see if they really repeat...

**Comment by cracker0dks** [comment]
I found out, rapidgator is using: https://www.solvemedia.com/security/index.html
So I don't think they repeat, but I collect a few, just to be sure.

**Comment by AlanTuring1978** [comment]
> 

lol I too immediately thought rapidgator must be way easier to solve (compared to others), didn't think all of this stuff through lmao

**Comment by AlanTuring1978** [comment]
> Yeah as human it seems to be easier... but we have different things that makes it complicated
> 
> 1. Different fonts (we cant just train it to one font like the k2s captcha. The generator for my training data also needs to support different fonts
> 2. we have words, so we need to detect spaces in between them
> 3. Placement and angle is random (The generator needs to support this)
> 4. We also have distortion sometimes (The generator needs to support this)
> 5. We dont have a fixed length of captchas chars (We cant proof and remove weak detected chars)
> 
> So I think I try to build a captcha database for rapidgator and see if they really repeat...

lol I too immediately thought rapidgator gotta be way easier to solve (compared to others), didn't think all of this stuff through lmao

**Comment by AlanTuring1978** [comment]
> Yeah as human it seems to be easier... but we have different things that makes it complicated

lol I too immediately thought rapidgator gotta be way easier to solve (compared to others), didn't think all of this stuff through lmao
