### ISSUE TITLE
i want to add this

### ISSUE THREAD

**Issue by rabeaasd** [cracker0dks/CaptchaSolver#18]
please i want a solve for this type of captcha
![captcha](https://user-images.githubusercontent.com/57960309/217000532-b5632153-fe3b-475f-ad1b-53e5ac675390.png)

**Comment by cracker0dks** [comment]
Where is  that from (hoster)?
Are you able to write a generator for that type of captcha?

**Comment by rabeaasd** [comment]
bot on  discord named probot , its used to transfer the currency of the bot

**Comment by rabeaasd** [comment]
![10348](https://user-images.githubusercontent.com/57960309/217098538-a14b0ad2-dbb2-4d7c-8932-cd98c75e61d1.png)
![11673](https://user-images.githubusercontent.com/57960309/217098545-ba8e6dbb-2269-4a45-8236-9186f2d851c3.png)
![11696](https://user-images.githubusercontent.com/57960309/217098546-f7020e4a-9577-4fce-9403-273c5cc49d12.png)
![12634](https://user-images.githubusercontent.com/57960309/217098553-5fb74ff2-575c-41ff-a046-9f6645b4d166.png)
![12697](https://user-images.githubusercontent.com/57960309/217098557-8696ed20-2442-4348-af4e-cc8d9fbc68bf.png)
![12770](https://user-images.githubusercontent.com/57960309/217098562-b860a354-ea25-4915-b864-10bb14df56e4.png)
![13273](https://user-images.githubusercontent.com/57960309/217098564-7126f78b-1592-4618-97e7-c0f14a52038d.png)
![13777](https://user-images.githubusercontent.com/57960309/217098568-04654020-1eff-4d7c-9c90-00a7d2e238e1.png)
![15601](https://user-images.githubusercontent.com/57960309/217098576-22aba727-2ed1-497e-b126-0ba442a35d85.png)
![15659](https://user-images.githubusercontent.com/57960309/217098582-f059b7c9-1877-4ada-af9d-c63edb0c7605.png)
![15662](https://user-images.githubusercontent.com/57960309/217098586-2797762a-4d51-49ab-9aae-09c68b2e4a3f.png)
![16461](https://user-images.githubusercontent.com/57960309/217098593-53a89e38-e2e8-4d52-9ad3-9e99fa2d00f6.png)
i have these examples

**Comment by cracker0dks** [comment]
sorry cant help you with that. Would need about 10-20k labled captchas to train the net. If you can provide them, I will train a net for you, I dont have the time to create them atm.

**Comment by rabeaasd** [comment]
> sorry cant help you with that. Would need about 10-20k labled captchas to train the net. If you can provide them, I will train a net for you, I dont have the time to create them atm.

i got 1100 captchas with their solve is that enough to train ?

**Comment by cracker0dks** [comment]
I could try, but we also need the data of the bounding boxes. So where in the image the char is. 
like this: 
![image](https://user-images.githubusercontent.com/1816621/217337203-cf481f8d-91bb-43d5-81cd-13b90c43a7c6.png)
If you dont have this data, you need to lable by hand... but it would be easier to generate that kind of captcha with your own code (with the bounding box data). That whay you could generate as much captchas as you want.

**Comment by rabeaasd** [comment]
> t it would be easier to generate that

how much captchas we need with their boxes to get the bot trained

**Comment by cracker0dks** [comment]
Take a look here: https://github.com/cracker0dks/CaptchaSolver/blob/master/docs/howToSolveNew6DigitCaptchasWalkthrough.md

There is all you need to know (and more) :)
We dont have a implementation to connect to discord, so even if we have a trained net, you would need the connection to discord.
