### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by AlanTuring1978** [cracker0dks/CaptchaSolver#19]
MacOS: For Intel Macs (Latest)
NodeJS: Installed via Homebrew (Latest)
Tried both **Precompiled** then tried **Compile darknet on your own** method both didn't work.

Just to mention, I'm kinda nube in this territory.
But for **Compile darknet on your own** method it seemed complied fine for me. Here's an screenshot: 
<img width="333" alt="Screenshot 2023-05-28 at 1 01 18 PM" src="https://github.com/cracker0dks/CaptchaSolver/assets/52377889/1a4a36cc-8ac7-49c5-8456-b00feb183e54">
(Based on this: https://pjreddie.com/darknet/install/ it is complied correctly I guess)

Here's a video inside the JD2 app like what it's doing:
https://github.com/cracker0dks/CaptchaSolver/assets/52377889/7d54e207-ebbc-49fe-a203-1fddf3e7ad92

**Comment by AlanTuring1978** [comment]
Just did this as mentioned here: (https://pjreddie.com/darknet/yolo/) and now I can say confidently darknet is working too.
Screenshot: 
<img width="1045" alt="Screenshot 2023-05-28 at 1 56 54 PM" src="https://github.com/cracker0dks/CaptchaSolver/assets/52377889/568a9d53-a18e-4570-be31-e296c1589d33">

Also tbt I'm not 100% sure what the step 3 in **Compile darknet on your own** method mean. Do I copy and paste all file from Darknet folder to /JDownloader 2.0/tools/offlineCaptchaSolver/darknet64/ folder or I'm missing smthn.

btw here's my test.bat file screenshot: 
<img width="992" alt="Screenshot 2023-05-28 at 1 38 25 PM" src="https://github.com/cracker0dks/CaptchaSolver/assets/52377889/0cf7332d-9ae3-4a45-a24d-3c7dac8e6c66">

**Comment by cracker0dks** [comment]
I don't have a mac and can't really help you with that, sry.
But take a look here please: https://github.com/cracker0dks/CaptchaSolver/issues/7
This should answer a lot of questions you have. Maybe I should put this into the mac install readme?

The test.bat is only a test working on windows (for debugging if you miss a windows .dll file)

**Comment by AlanTuring1978** [comment]
Ok so what I've learned from #7 is I've got most of thing right already. But the issue's are atm with the node and npm.

Here's my log file:
<img width="766" alt="Screenshot 2023-05-28 at 8 10 59 PM" src="https://github.com/cracker0dks/CaptchaSolver/assets/52377889/3a1808b5-b40a-4761-8c2f-c29aa37a932a">

Node and Npm usually resides in here:
<img width="178" alt="Screenshot 2023-05-28 at 8 00 30 PM" src="https://github.com/cracker0dks/CaptchaSolver/assets/52377889/02446ff0-1894-422a-9cb8-47cf0ced791f">

Lol I'm into it now, so I'm ready to help mate if you need any btw :)

**Comment by cracker0dks** [comment]
try to run "npm install" in this folder: "JDownloader 2.0/tools/offlineCaptchaSolver" and try again. Your npm modules are missing.

**Comment by AlanTuring1978** [comment]
Lol I was trying to `npm install` on the wrong directory. Anyways it works

**Comment by AlanTuring1978** [comment]
Error is gone but the new error occurs.

Running -> keep2share.cc
keep2share.cc
/bin/sh: ./darknet: is a directory
node:child_process:960
    throw err;
    ^

Error: Command failed: cd darknet64 && ./darknet detector test data/obj.data yolov4-tiny-custom.cfg yolov4-tiny-custom_last.weights -dont_show temp.jpg
/bin/sh: ./darknet: is a directory

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Timeout._onTimeout (/Applications/JDownloader 2.0/tools/offlineCaptchaSolver/ocr.js:71:30)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  status: 126,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(35) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,  58,
       32,  46,  47, 100,  97, 114, 107, 110,
      101, 116,  58,  32, 105, 115,  32,  97,
       32, 100, 105, 114, 101,  99, 116, 111,
      114, 121,  10
    ]
  ],
  pid: 44787,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(35) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,  58,
     32,  46,  47, 100,  97, 114, 107, 110,
    101, 116,  58,  32, 105, 115,  32,  97,
     32, 100, 105, 114, 101,  99, 116, 111,
    114, 121,  10
  ]
}

Node.js v20.1.0

**Comment by AlanTuring1978** [comment]
ok I resolves the following error

**Comment by AlanTuring1978** [comment]
Now the log file is:
{
  "host": "keep2share.cc",
  "text": "vhgO7E",
  "confidence": 95
}

**Comment by AlanTuring1978** [comment]
lol what a hell of a ride it was. I'll create a simple follow to guide text some hour later with some thought, like go back and see what I did right and wrong, as a fresh start of everything as a new user perspective. And thanks mate :)

**Comment by AlanTuring1978** [comment]
**Ok let me address some things from #7 for future reader.**

There is some stuff @sevigny245 got wrong,
1. Like put the `darknet` folder into `darknet64`. (https://github.com/cracker0dks/CaptchaSolver/issues/19#issuecomment-1566350310)
2. Plus Installing `darknet` main repo i.e. `https://pjreddie.com/darknet/install/` and compiling it didn't work for me altho I tried with opencv off only (didn't tried with opencv on cause I think maybe there's some file missing or smthn that we'll need for CaptchaSolver so I didn't go for extra hassle to turning it on). But `https://github.com/AlexeyAB/darknet` forked repo worked I tried it with opencv on (haven't tried with opencv off cause turning opencv on was easier on this).
3. Plus there is `node_modules` missing in his folder too.

**Note:** if you are new like I was, you should know that darknet uses opencv for variety of image support and online image support that's it (you can learn more about here: https://pjreddie.com/darknet/install/). There is also CUDA thing if you want GPU computation. But in mac we can't run Nvidia's CUDA (as nvidia and apple aren't friends lol), so we don't have to worry bout that and we'll run it via CPU.

**Comment by cracker0dks** [comment]
Thanks for your input, I think I will add this into the readme 👍

**Comment by AlanTuring1978** [comment]
**And here's my final follow to guide. I'll choose homebrew as it is the most popular package manager.**

```
1. brew install node && brew install cmake && brew install opencv
3. git clone https://github.com/AlexeyAB/darknet
4. cd darknet
5. mkdir build_release
6. cd build_release
7. cmake .. -DENABLE_CUDA=OFF -DOpenCV_DIR=/usr/local/Cellar/opencv/cmake
8. cmake --build . --target install --parallel 8
9. ..
10. vi makefile
```
11. Then edit OPENCV=0 to 1
You can use nano to edit the text file too as it is way easier. For nano just do:
- `nano makefile`
- edit OPENCV=0 to 1
- press control x
- then y
- then enter

Troubleshoot to see if `darknet` is working with `opencv` correctly: `cd ~/darknet && ./darknet imtest data/eagle.jpg`

12. git clone https://github.com/cracker0dks/CaptchaSolver.git
13. cd ~/CaptchaSolver/JDownloader\ 2.0/tools/offlineCaptchaSolver
14. npm install

**That's it, you are all set on `darknet` & `CaptchaSolver`**
OK now while you still in this directory in the terminal do this to ensure this files executable: `chmod +x filejoker.sh keep2share.cc.sh checkdeps.sh`
Check node & npm location by `which node` & `which npm`(Isn't necessary cause it should be in the same location for everyone who installed it via brew)
Next we'll edit this path to the `filejoker.sh keep2share.cc.sh checkdeps.sh`
Again using vi here but obvs u can use nano and instructions the same.
`vi keep2share.cc.sh`
Edit `node` to `/usr/local/bin/node`
`vi filejoker.sh`
Edit `node` to `/usr/local/bin/node`
`vi checkdeps.sh`
Edit `npm` to `/usr/local/bin/npm`
`Cd`
1. `cp -rf ~/darknet/. ~/CaptchaSolver/JDownloader\ 2.0/tools/offlineCaptchaSolver/darknet64`
(Copy and merge darknet content to CaptchaSolver)
3. `cp -rf ~/CaptchaSolver/. /Applications/JDownloader\ 2.0`
(Copy and merge CaptchaSolver content to JDownloader 2 app folder)
5. `rm -rf /Users/utsho/CaptchaSolver /Users/utsho/darknet`
(Remove the duplicate `darknet` & `CaptchaSolver` directory from your user home directory as it'll no longer needed by `CaptchaSolver`)

Finally you can open JDownloader app and try to download, if it didn't work in a minute or 2 stop or disable the specific download and start it again. If still it didn't work just see the log file in `/Applications/JDownloader\ 2.0/tools/offlineCaptchaSolver/log.txt` and ask us the community I guess.

**Comment by AlanTuring1978** [comment]
@cracker0dks 👆

**Comment by cracker0dks** [comment]
thank you very much for this create tutorial 🥳

**Comment by AlanTuring1978** [comment]
@cracker0dks of course mate and thank you for creating this. Least I can do, as this'll save me ton of hassle as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

**Comment by AlanTuring1978** [comment]
One more thing is browser based captcha e.g. depositfiles is functional as of now?

**Comment by AlanTuring1978** [comment]
> thank you very much for this create tutorial 🥳

Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha every hour as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing is browser based captcha e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't even tried to solve it.

**Comment by AlanTuring1978** [comment]
> thank you very much for this create tutorial 🥳

Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha every hour as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing is browser based captcha e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it (I checked the log).

**Comment by AlanTuring1978** [comment]
Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing is browser based captcha e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it (I checked the log).

**Comment by AlanTuring1978** [comment]
Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it (I checked the log).

**Comment by AlanTuring1978** [comment]
Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it.

**Comment by AlanTuring1978** [comment]
Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it. Altho I use this [open source project ](https://github.com/dessant/buster) but it's very simple like uses google speech to text to solves audio not in the level like what u are doing lol.

**Comment by AlanTuring1978** [comment]
Of course mate and thank you for creating this. Least I can do, as this'll save me hassle/wasting time solving captcha as I usually downloads chunk file (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles is functional or in the plan? Cause for me It worked one time when the browser didn't ask for reCAPTCHA and it just had to select I'm not a robot, but when the browser asked for reCAPTCHA it didn't tried to solve it. Altho I use this [open source project](https://github.com/dessant/buster) but I have to manually interact and it's very simple like uses google speech to text to solves audio not in the level like what u are doing lol.

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very lightweight and simple uses like google speech to text to solve audio, not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very lightweight and simple uses like google speech to text to solve audio, not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very lightweight and simple uses like google speech to text to solve audio, not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very lightweight and simple, uses like google speech to text to solve audio, not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very lightweight and simple, uses like google speech to text to solve audio not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very simple, uses like google speech to text to solve audio not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very simple, uses like google speech to text to solve audio not at the level of what you're doing lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's very simple, uses like google speech to text to solve audio

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with and It's kinda simple, uses like google speech to text to solve audio not at your scale lol

**Comment by AlanTuring1978** [comment]
Of course mate and for creating this! Least I can do, this'll save me hassle/wasting time solving captcha as I usually downloads chunk files (100mb+-). Plus it's really cool what u are doing :)

One more thing, is browser based reCAPTCHA e.g. depositfiles functional or in the plan? cause for me it worked once when the browser didn't ask for reCAPTCHA, but it didn't try to solve it when it did. altho I use this [open source project](https://github.com/dessant/buster), but I have to manually interact with it, uses like google speech to text to solve audio

**Comment by cracker0dks** [comment]
solving reCaptcha is not part of this repo, but depositfiles should have the same captcha as the others (only filejoker.net is different). Or did they change something?

rapidgator is discussed here (And why we can not support it for now): https://github.com/cracker0dks/CaptchaSolver/issues/17#issuecomment-1399550999

**Comment by cracker0dks** [comment]
ok, than they changed that :(
I'll update the readme, thanks

**Comment by AlanTuring1978** [comment]
hey @cracker0dks I found a minor issue with filejoker. Cause keep2share works like a charm but with filejoker it is like hit or miss scenario. Sometime in log file it shows that it has solved the captcha, but still the download process don't starts. Plus sometimes it also throws this error:
```
Running -> filejoker.net
filejoker.net
0 4 Corners 2954
1 Circle 4116
2 Circle 4230
3 4 Corners 2861
4 Circle 4205
5 3 Corners 2359
6 6 Corners 3479
7 5 Corners 3088
8 Circle 4319
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (3)
    at Object.writeFile (node:fs:2276:5)
    at /Applications/JDownloader 2.0/tools/offlineCaptchaSolver/ocr.js:34:12
    at /Applications/JDownloader 2.0/tools/offlineCaptchaSolver/ocr.js:215:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.2.0
```

**Comment by AlanTuring1978** [comment]
Anything I can try to resolves this?

**Comment by AlanTuring1978** [comment]
Sorry for the late reply, I've tried to reproduce the `node:internal/errors:490
    ErrorCaptureStackTrace(err);` but after changing the `ocr.js` I couldn't reproduce the error plus very surprisingly I never really got that stuck scenario anymore and somehow it's kinda working, I dunno what was the issue!
