### ISSUE TITLE
Captcha Solver not working with me in windows

### ISSUE THREAD

**Issue by smarafa22** [cracker0dks/CaptchaSolver#22]
Hi

I downloaded  and installed your Captcha solver as your instructions (my OS is Windows 11) but after that it is not working ,
So is there an another configuration should be set ? in Captches window still i select "Dialog  (windows) in jdownloader" service and i don't show service  as "Offline Captcha solver" , how i activate Offline Captcha solver in jdownloader?

Thanks

**Comment by cracker0dks** [comment]
Hey,
did you check: https://github.com/cracker0dks/CaptchaSolver#troubleshooting-windows

Inside jdownloader you will not see the captcha solver as extra service. The scripts are running under "JAntiCaptcha" lable in Settings->Captchas

**Comment by smarafa22** [comment]
Thanks a lot for your reply , now it is working.
Can your captcha solver support uloz.to host ?

**Comment by smarafa22** [comment]
Here some samples 

![uloz to 1](https://github.com/cracker0dks/CaptchaSolver/assets/142555260/9a377a6a-184c-405f-9b7b-16a991752881)

![uloz to 3](https://github.com/cracker0dks/CaptchaSolver/assets/142555260/e921c0d4-4076-4463-941b-563633cb44f9)

![uloz to 2](https://github.com/cracker0dks/CaptchaSolver/assets/142555260/5b470fb7-1f2f-4dbb-9171-507a9d921130)


![uloz to 4](https://github.com/cracker0dks/CaptchaSolver/assets/142555260/38dcba91-dd4b-4574-a41e-e04e96e6eede)

![uloz to 5](https://github.com/cracker0dks/CaptchaSolver/assets/142555260/bfcd3108-5511-496f-b040-d7c73056fadc)
