### ISSUE TITLE
Broken on k2s

### ISSUE THREAD

**Issue by mschumacher69** [cracker0dks/CaptchaSolver#24]
Hi, this doesn't seem to be working on k2s anymore.

**Comment by cracker0dks** [comment]
seems to be on your end. Still working for me (tested a few minutes ago)

**Comment by mschumacher69** [comment]
There was an update to JD and now there's another update, I will keep monitoring and let you know if it's still not working.

**Comment by mschumacher69** [comment]
Oh wait, it works, it just seems to be popping up at first and then it auto solves. Earlier, it used to auto solve in the background if I remember correctly.

**Comment by cracker0dks** [comment]
yeah, the very first time this is normal. After that it should work. If not, please reopen.
