### ISSUE TITLE
How to resolve one digit captcha

### ISSUE THREAD

**Issue by GinoGreen** [cracker0dks/CaptchaSolver#25]
Hi, can you create a guide about "How to resolve one digit captcha" with tesseract.js and jimp?
I'll show you some example images of real cases:
![0](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/bf91ada5-d1aa-4786-b029-dbd1051338d1)
![1](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/1cb36af4-fbb5-457e-9717-ae208cc59b38)
![5](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/37c82e71-8741-4e37-be23-c61757954cd7)

I'm trying to extract the number from the image, but very bad results.
I thought the problem was the double background that conflicts with the digit, for this reason I created an additional function to try to unify the background color.
`
app.post(
   "/api/watch_videos",
   async (req, res) => {
      try {
         const browser = await puppeteer.launch({
            headless: false,
            executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', // Specify the path to Google Chrome
            args: ['--disable-web-security', '--mute-audio'], // Disable web security
         });
         const videoLinks = req.body.videoLinks;
         const cookies = splitCookies();

         for (const link of videoLinks) {
            const page = await browser.newPage();

            await page.setCookie(...cookies);

            // Go to the website
            await page.goto(
               `https://placeholder.etc/${link}`
            );

            if (!isCaptchaRequired(page)) {
            // do my stuff
               
            } else {
               console.log("Captcha found, enter here");
               // Here, you need to solve the images with tesseract.js
               await page.waitForSelector('img[src^="data:image/jpeg;base64"]');
               const images = await page.$$eval('img[src^="data:image/jpeg;base64"]', imgs => imgs.map(img => img.getAttribute('src')));
               const imagesText = await page.$eval('.container-fluid h3.text-center', (element) => element.innerHTML);

               if (images && images.length > 0) {
                  // Use the map() method to remove the initial part from each URL
                  const modifiedImages = images.map((imageUrl) => {
                     // Use the substring() method to remove "data:image/jpeg;base64,"
                     const modifiedUrl = imageUrl.substring("data:image/jpeg;base64,".length);
                     console.log(modifiedUrl.substring(0, 20));
                     return modifiedUrl;
                  });
                  let srcSx = []
                  let srcDx = []
                  switch (images.length) {
                     case 2:
                        srcSx.push(modifiedImages[0]);
                        srcDx.push(modifiedImages[1]);
                        break;

                     case 3:
                        srcSx.push(modifiedImages[0]);
                        const parts = imagesText.split("> + <");
                        const lastPart = parts[parts.length - 1];
                        const match = lastPart.match(/src="data:/g)
                        console.log(match);
                        if (match && match.length > 1) {
                           srcDx.push(modifiedImages[1]);
                        } else {
                           srcSx.push(modifiedImages[1]);
                        }
                        srcDx.push(modifiedImages[2]);
                        break;

                     case 4:
                        srcSx.push(modifiedImages[0]);
                        srcSx.push(modifiedImages[1]);
                        srcDx.push(modifiedImages[2]);
                        srcDx.push(modifiedImages[3]);
                        break;

                     default:
                        break;
                  }
                  if (srcSx.length > 0 && srcDx.length > 0) {
                     console.log("srcSx.length ", srcSx.length);
                     console.log("srcDx.length ", srcDx.length);

                     const worker = await createWorker('eng');

                     (async () => {
                        await worker.setParameters({
                           tessedit_char_whitelist: '0123456789',
                           user_defined_dpi: '300', // Set the desired resolution (300 DPI)
                        });
                        for (const base64 of srcSx) {
                           const imageBuffer = Buffer.from(base64, 'base64');
                           const imageBufferModified = await modifyBackground(imageBuffer);
                           const {
                              data: {
                                 text
                              }
                           } = await worker.recognize(imageBufferModified, "eng");
                           console.log(`Text from srcSx: ${text}`);
                        }

                        for (const base64 of srcDx) {
                           const imageBuffer = Buffer.from(base64, 'base64');
                           const imageBufferModified = await modifyBackground(imageBuffer)
                           const {
                              data: {
                                 text
                              }
                           } = await worker.recognize(imageBufferModified, "eng");
                           console.log(`Text from srcDx: ${text}`);
                        }
                        await worker.terminate();
                     })();
                  }
               }
            }
         }

         // Close the browser at the end
         await browser.close();

         res.status(200).send(
            "Videos watched successfully."
         );
      } catch (error) {
         console.error(error);
         res.status(500).send(
            "Error while watching the videos."
         );
      }
   }
);

async function modifyBackground(imageBuffer) {
   return new Promise((resolve, reject) => {
      sharp(imageBuffer)
         .raw()
         .toBuffer(async (err, buffer, info) => {
            if (err) {
               reject(err);
               return;
            }

            const width = info.width;
            const height = info.height;
            const channels = info.channels;

            // Define a threshold to determine if a color is "close" to white or black
            const threshold = 10; // Adjust this value as needed

            // Read the color of the first pixel in the upper left
            const firstPixelIndex = 0;
            const firstPixelRed = buffer.readUInt8(firstPixelIndex);
            const firstPixelGreen = buffer.readUInt8(firstPixelIndex + 1);
            const firstPixelBlue = buffer.readUInt8(firstPixelIndex + 2);

            // Calculate the opposite color
            const newBackgroundColor = {
               red: 255 - firstPixelRed,
               green: 255 - firstPixelGreen,
               blue: 255 - firstPixelBlue,
            };

            // Iterate through the pixels of the image
            for (let y = 0; y < height; y++) {
               for (let x = 0; x < width; x++) {
                  const pixelIndex = (y * width + x) * channels;

                  // Read the color channels of the pixel
                  const red = buffer.readUInt8(pixelIndex);
                  const green = buffer.readUInt8(pixelIndex + 1);
                  const blue = buffer.readUInt8(pixelIndex + 2);

                  // Check if the pixel color is close to white or black
                  if (
                     Math.abs(red - firstPixelRed) <= threshold &&
                     Math.abs(green - firstPixelGreen) <= threshold &&
                     Math.abs(blue - firstPixelBlue) <= threshold
                  ) {
                     // Change the color of the pixel to the new background
                     buffer.writeUInt8(newBackgroundColor.red, pixelIndex); // R
                     buffer.writeUInt8(newBackgroundColor.green, pixelIndex + 1); // G
                     buffer.writeUInt8(newBackgroundColor.blue, pixelIndex + 2); // B
                  }
               }
            }

            const modifiedImageBuffer = await sharp(buffer, {
                  raw: {
                     width,
                     height,
                     channels,
                  },
               })
               .toFormat('png')
               .toBuffer();

            // Now buffer contains the image data with the new background based on the opposite of the first pixel
            resolve(modifiedImageBuffer);
            // Save the resulting image to see the result (TEST)
            sharp(buffer, {
                  raw: {
                     width,
                     height,
                     channels
                  }
               })
               .toFile('modified_image.png', (err) => {
                  if (err) {
                     console.error('Error saving: ", err);
                  } else {
                     console.log('Success saving');
                  }
               });

         });
   });
};
`
This is the difference between per-unifying background color -> post-unifying background color
PRE:
![2](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/6b83af3c-6636-48c5-89ad-f08e87533c63)
POST:
![immagine_modificata](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/5b7c4d8a-ecbc-4b0a-8e99-ad71542c9514)

**After all this, tesseract still fails to extract the number**
You might say that I'm just complicating my life, and surely the answer is "yes",
but I'm here to look for a more _effective solution_. 

Thanks

**Comment by cracker0dks** [comment]
Im not using tesseract anymore... its not very usefull with captcha letter if they are not perfectly extracted from the background and not tilted. I would use a nuronal network  like did here: https://github.com/cracker0dks/CaptchaSolver/blob/master/docs/howToSolveNew6DigitCaptchasWalkthrough.md#next-level-and-my-solution-train-a-neuronal-network
If you need a tool to create labled captchas to train the network I could upload the one Ive created back then :)

**Comment by GinoGreen** [comment]
With labled captchas do you mean that each image representing a digit is associated with its specific number? all this in a pre-established way? It can be a good idea in my case, because I have 10 digit images , with 4 variants.

**Comment by cracker0dks** [comment]
yes, the best way would be to train it yourself. 
You would need about 10000 labeld images. Means the image and an extra file with the bounding box(es) from the object(s) in the given image. Take a look at this tool Ive wrote (just open the index.html in chrome). 
[captchaTool.zip](https://github.com/cracker0dks/CaptchaSolver/files/13265402/captchaTool.zip)
You would need to implement your own captcha type to generate the captcha and the labels.txt then train the network :)

**Comment by GinoGreen** [comment]
Since I'm not very expert in this type of operation, I divided the work into steps:
- generate captchas as similar as possible to the originals
- understand how I can train darkyolo (by docs)
- train it
- test it
I'm stuck at the first step as I don't think I was able to generate captchas similar to the original captchas.

![Screenshot 2023-11-06 145701](https://github.com/cracker0dks/CaptchaSolver/assets/88828804/82848e78-9a05-47e3-b72b-930e73313e34)


Can I ask you for a hand?

Thank you

**Comment by cracker0dks** [comment]
If your numbers are always the same (size and rotation)? Then you could mark them by hand sure :)
If not I give it a try with the tool  to recreate your captcha type.

**Comment by GinoGreen** [comment]
Yes my numbers are ever the same. Both size and rotation. With "mark them by hand" do you mean with [https://github.com/AlexeyAB/Yolo_mark](Yolo mark)?

**Comment by cracker0dks** [comment]
yes exactly

**Comment by GinoGreen** [comment]
thank you for your help <3
