### ISSUE TITLE
Cant compile for Raspberry Pi Zero w (arm 32)

### ISSUE THREAD

**Issue by Spb2005** [cracker0dks/CaptchaSolver#27]
Hi, 
ive tried to compile it for my Raspberry Pi Zero w which is Arm 32, but i could´nt get it to work. 
I ve never compiled something on my Raspberry pi,  is there another way? 
Is it easier to compile the tar.gz file?
Could you compile it for me?
Thanks

**Comment by cracker0dks** [comment]
sry, cant help you on that. You would need to compile the yolo darknet thing and I dont know if they even support that.
