### ISSUE TITLE
Letter I - lower & upper cases causing inappropriate recognition results

### ISSUE THREAD

**Issue by EdgarBlack2** [cracker0dks/CaptchaSolver#28]
Hey cracker0dks,

first of all I want to express my highest appreciation for your 6-lettercase OCR of captchas working extremely well. After having tested your script since 6 months I just discovered one challenge. Whenever the captchas did contain a lowercase letter "i" or uppercase letter "I" this would lead to double recognitions of this same letter as in your discovered font the lower & upper case letter "I" are exactly the same. Any chance you could further improve your recognition script to encounter this little challenge?

Thanks & BR,
Edgar

**Comment by EdgarBlack2** [comment]
Thanks for the quick feedback. As I am currently still on vacation not having full access to my virtual machines I will share an example w/ you early next week.

What actually happens when just one "i" or "I" image is screened in the captchas is that the OCR script does call-out the "I" letter twice as from my impressions the OCR does come to the conclusion that both letter cases show a high OCR confidence level. 

So my request is not to differentiate between "i" or "I" as this is just impossible (being the same letter case in that font) but to avoid that the one image letter leads to two recognitions of this one letter.

I hope that my explanation does give you more insights into my challenge. As mentioned I will be able to provide an example by next week. ;)

**Comment by fredo-47** [comment]
I think, @EdgarBlack2 you are saying that an image like "EfGhI" is solved to "EfGhIl", i.e. the image of the last letter "I" is solved to two letters: small "L" and capital "i"?

**Comment by EdgarBlack2** [comment]
Correct... due to the captcha script limit to 6 letters I have realized that often times the last none-I char is just cut-off leading to captcha failure.

**Comment by EdgarBlack2** [comment]
Just one adhoc example... the following captcha... ![index](https://github.com/cracker0dks/CaptchaSolver/assets/46560102/8bce0e93-f1a8-4631-bc0d-40aa976f2577)

... is resulting into "uXIlmr" using your highly appreciated OCR script. That means the following char gets replaced by another "I" letter as the script get's confused trying to differentiate between lower and upper letter cases of "I". I thought about changing the char range blanking either the lower or upper case "I" char but that destroyed the complete OCR script leading to high failure rates.

Any guidance how to fix this challenge would be highly appreciated. ;)

**Comment by cracker0dks** [comment]
I added this lines into the [ocr.js](https://github.com/cracker0dks/CaptchaSolver/blob/master/JDownloader%202.0/tools/offlineCaptchaSolver/ocr.js#L86)
 
````
for(var i = valdResA.length-1; i>=0; i--) { //Remove "I" because big "i" and small "L" -> "l" have the same char in this font
    if(valdResA[i]["c"] == "I") {
        valdResA.splice(i, 1);
    }
}
````
The proper way would be to train the network again without on of the chars... But this workaround sould do it for now. What do you think?

**Comment by EdgarBlack2** [comment]
@cracker0dks, thanks for this code snippet. As I do not have full access to my virtual machine being out of town till end of this week for vacation I will test your improved script early next week. I am pretty confident that your code bypass should fix this challenge without having to train YOLO once more. But based on your incredible captcha creator the retraining should be an easy task I will also give it a try in the coming weeks. ;-)

I let you know during next week if the code improvement did fix this challenge.

Thanks again for your outstanding work on GitHub. It is just great how you are sharing your work in full transparency and also granting extremely quick support.

**Comment by EdgarBlack2** [comment]
Works as now all duplicate small "l" (like lucky) and big "I" (like Insane) are not recognized 2 times. If I find some time in the coming weeks & months I might leaverage your incredible captcha creator to consider this challenge riof the right in the YOLO training file.

Thanks again for your outstanding support! Looking forward to follow any of your new projects! ;)
