### ISSUE TITLE
Add "dfiles.eu" and "fboom.me" to jacinfo.xml

### ISSUE THREAD

**Issue by fredo-47** [cracker0dks/CaptchaSolver#29]
Hello,

the keep2share method is also valid for "dfiles.eu" and "fboom.me".

Could you please add these two services ("dfiles.eu" and "fboom.me") to the `jacinfo.xml` files located in the `JDownloader 2.0/jd/captcha/methods/keep2share_*` folders?

Thank you!

**Comment by cracker0dks** [comment]
thanks, I added them 👍
