### ISSUE TITLE
how to recruit this for a different host?

### ISSUE THREAD

**Issue by quidnun** [cracker0dks/CaptchaSolver#5]
Hi, sorry to bother you. This looks cool. I wanted to use this for Tezfiles.com instead of keep2share and the captcha looks the same. Is there a simple thing I can do to make it use this engine for that instead of for keep2share?

**Comment by cracker0dks** [comment]
yes, should be easy. Just add `tezfiles.com;` to the hostfile: JDownloader 2.0\jd\captcha\methods\keep2share_win\jacinfo.xml (for win, on linux use the other file) so it looks like this:
```
<jDownloader>
  <method type="extern" os="windows" name="kscaptcha_win" services="keep2share.cc;fileboom.me;depositfiles.com;tezfiles.com;" />
  <command cmd="tools\offlineCaptchaSolver\keep2share.cc.bat" src="tools\offlineCaptchaSolver\input.gif" dst="tools\offlineCaptchaSolver\result.txt" />
</jDownloader>
```
Then restart jdownloader. This should do the job.
Thanks for letting me know, I will add this to the next release 👍

**Comment by quidnun** [comment]
oh, ok I did see this

https://jdownloader.org/knowledge/wiki/development/captcha/extern-captcha-method

but I was confused by the directory name being keep2share_win

Thanks

It appears to be working, aside from it still sending notifications to the manual captcha on my fine (still trying to figure out how or if it's possible to disable manual for one host)

**Comment by cracker0dks** [comment]
nice, can't help you with your phone problem
