### ISSUE TITLE
How can I recognize the second sample?

### ISSUE THREAD

**Issue by gabriel-fsa** [cracker0dks/CaptchaSolver#6]
How can I recognize the caracteres about this image https://github.com/cracker0dks/CaptchaSolver/blob/master/docs/ksinput.gif .

**Comment by cracker0dks** [comment]
Docu how I solved it here: https://github.com/cracker0dks/CaptchaSolver/blob/master/docs/howToSolve6DigitCaptchasWalkthrough.md

Code should be in this release: https://github.com/cracker0dks/CaptchaSolver/releases/tag/v1.4.3_Standalone
