### ISSUE TITLE
I'm having a hell of a time trying to install this on Mac

### ISSUE THREAD

**Issue by sevigny245** [cracker0dks/CaptchaSolver#7]
Not sure what I'm doing wrong. I believe I'm following every instruction. Granted I am a total newbie at this but I'm finding it very frustrating lol

My node.js is 14.15.5 according to node -v
when i follow that up with echo $PATH I get
![Screen Shot 2021-02-11 at 1 33 14 AM](https://user-images.githubusercontent.com/21232352/107615380-4b5fb100-6c09-11eb-93b5-a4a56017572e.png)

I compiled darknet according to this tutorial https://pjreddie.com/darknet/install/
substituting AlexeyAB's fork instead of pjreddie's from the tutorial.

I used "make" with OpenCV since my Mac doesn't have CUDA and I succeeded in getting a bunch of windows with eagles to show up when I tested it (as per that tutorial), proving I'd compiled darknet correctly.

Then I plugged it into jDownloader 2.0 as specified in the instructions
![Screen Shot 2021-02-11 at 1 45 17 AM](https://user-images.githubusercontent.com/21232352/107616227-e1480b80-6c0a-11eb-97e6-2a5d2653399c.png)

Along with the content from the CaptchaSolver git repository
![Screen Shot 2021-02-11 at 1 40 18 AM](https://user-images.githubusercontent.com/21232352/107615898-3b949c80-6c0a-11eb-95b7-a5c28b45479a.png)
When I clone this repository, I find keep2share_linux and keep2share_win for placing in captcha -> methods, is there a missing keep2share_mac perhaps? Or keep2share_osx?

Anyway, even after multiple restarts, jDownloader 2.0 still makes me solve Captchas manually. Arg.

I will say I tried this on a Windows machine with your standalone zip "win" install method and it worked flawlessly, which is amazing, but I really need it to work on my Mac lol please help!

**Comment by cracker0dks** [comment]
Sorry that you had to go through all this :D
Sound promising what you've done so far. You are right, we had the jacinfo.xml missing for mac so I added it with the correct parameters inside. I don't have a MAC but if all the other stuff is right, this could work. You need to put the new folder https://github.com/cracker0dks/CaptchaSolver/tree/master/JDownloader%202.0/jd/captcha/methods/keep2share_mac with content to the right place and try again.
 Hope this is working :)

**Comment by sevigny245** [comment]
Thank you so much! Okay so I plugged in the new file and it does instantly solve captchas, but the downloads stay stuck on "starting" regardless of how many captchas get solved. Erg.

**Comment by cracker0dks** [comment]
can you download the link through the website ? This is maybe a link problem, although I never seen it happen.

**Comment by sevigny245** [comment]
I've tried a few different links from k2s and fileboom and they all have the same problem. The problem wasn't there before installing CaptchaSolver. Also, I'm midway through downloading some things and now I get the "starting" hang on them as well after restarting jDownloader

Here's my install of the new keep2share_mac file
![Screen Shot 2021-02-11 at 2 36 44 PM](https://user-images.githubusercontent.com/21232352/107701821-a8de1700-6c76-11eb-80ca-7d16768989b8.png)

**Comment by cracker0dks** [comment]
On Mac could be that still is something wrong with the setup... but if you have this problem also on win (wich was working before), this is not really possible I think...

**Comment by sevigny245** [comment]
Yeah, I think something is still wrong with my Mac install, though I have no idea what it could be. For the record, I have two separate computers, a Mac and a PC. On the PC, jDownloader and CaptchaSolver work flawlessly. On Mac, I have both MacOS and Parallels Desktop running Windows virtually, with jDownloader running in both environments, two instances total simultaneously open on the same computer, the Mac. Both hang on "starting." 

jDownloader worked fine on Mac before installing CaptchaSolver, but now I get the hang whether I'm running jDownloader natively in MacOS or whether I'm running it in Windows via Parallels Virtualization on that same computer. Not sure why. Anyway, it's a niche situation. Thanks for trying to help! I appreciate you making that extra file for me, it definitely did something lol the captcha now auto-solves over and over on Mac but the download never actually "starts." So the solver definitely works now on Mac! That's something! Thank you!

**Comment by cracker0dks** [comment]
If it's running on a different Windows PC and not on your mac, it is probably laptop related so I have no Idea, maybe firewall?
Good luck :)

**Comment by hbfs** [comment]
Had the same issue with "starting" loop. 
checked `log.txt` in `JDownloader/log.txt` and `log.txt` in `JDownloader/tools/offlineCaptchaSolver/log.txt`
the script cant find `node` or `npm`, so there are a few solutions:

- if the commands work manually in your terminal, change the script shell from `/bin/bash` to `$SHELL` (`/bin/zsh`)
- use full path `/usr/local/bin/node` in the two scripts in `keep2share.cc.sh`. The same can be done for `npm` in `checkdeps.sh`, or manually install the node modules.
- create a `~/.bashrc` and ensure `node` and `npm` are in the path, eg. `export PATH=$PATH:/usr/local/bin`

**Comment by hbfs** [comment]
How to build on macOS Ventura 13.3.1 with macports 

1. Install dependencies
`sudo port install cmake`
`sudo port install nodejs18 npm9`
`sudo port install opencv4`

2. Clone `darknet` repo
`git clone https://github.com/AlexeyAB/darknet`

3. Build with `cmake`: 
`cd darknet`
`mkdir build_release`
`cd build_release`
`cmake .. -DENABLE_CUDA=OFF -DOpenCV_DIR=/opt/local/libexec/opencv4/cmake`
`cmake --build . --target install --parallel 8`

4. Copy to `darknet` to JDownloader 2
`cp -i darknet ~/JDownloader\ 2/tools/offlineCaptchaSolver/darknet64/`

**Comment by AlanTuring1978** [comment]
> How to build on macOS Ventura 13.3.1 with macports
> 
> 1. Install dependencies
>    `sudo port install cmake`
>    `sudo port install nodejs18 npm9`
>    `sudo port install opencv4`
> 2. Clone `darknet` repo
>    `git clone https://github.com/AlexeyAB/darknet`
> 3. Build with `cmake`:
>    `cd darknet`
>    `mkdir build_release`
>    `cd build_release`
>    `cmake .. -DENABLE_CUDA=OFF -DOpenCV_DIR=/opt/local/libexec/opencv4/cmake`
>    `cmake --build . --target install --parallel 8`
> 4. Copy to `darknet` to JDownloader 2
>    `cp -i darknet ~/JDownloader\ 2/tools/offlineCaptchaSolver/darknet64/`
> 
> Other notes:
> 
> * Use full paths in scripts:
>   
>   * `/opt/local/bin/node` in both scripts in `filejoker.sh` and `keep2share.cc.sh`.
>   * `/opt/local/bin/npm` in `checkdeps.sh`
>   * creating a `~/.bashrc` with `node` and `npm` in the path did not work.
>     
>     * `export PATH=/opt/local/bin:$PATH` did not work
> * Ensure `checkdeps.sh`, `filejoker.sh`, and `keep2share.cc.sh` are executable.
>   
>   * `chmod +x checkdeps.sh filejoker.sh keep2share.cc.sh`

Hey just a quick question does CaptchaSolver working on your mac now?

**Comment by hbfs** [comment]
> Hey just a quick question does CaptchaSolver working on your mac?

Yes, for the most part it works without issue on supported captchas. Every once in a while it will still prompt to solve a captcha. 

If you're having issues, what are the logs showing?

Also try manually running `npm install` in the tools folder.
