### ISSUE TITLE
I don't understand how to use it.

### ISSUE THREAD

**Issue by ice-devs** [cracker0dks/CaptchaSolver#9]
Hello! I am kind of lost of the commands I need to run to solve an image. Please be kind to provide me with some help on the subject. Example scenario: I have an image called captcha.png. What should I run to solve it and get the letters in the captcha?

**Comment by cracker0dks** [comment]
Sure, change your dir to: `CaptchaSolver\JDownloader 2.0\tools\offlineCaptchaSolver\darknet64`

Save your image there.
Then run (in cmd): 
`darknet_no_gpu.exe detector test data/obj.data yolov3tinyobj.cfg yolov3tinyobjLast.weights captcha.png`

If you don't want to see the result img (only console logs) add: `-dont_show`

**Comment by ice-devs** [comment]
Okay, thanks! One last thing. How can I set the characters that the captcha contains?

**Comment by cracker0dks** [comment]
set the characters into? back into jd2 ?

**Comment by ice-devs** [comment]
Never mind, figured it out. Thanks a lot! You have made an awesome piece of software! I'll close this now.
